# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.ManyToManyField(related_name='_category_categories_+', to='categories.Category'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
