# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20171125_1744'),
        ('products', '0002_auto_20171125_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='categories.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
